version: 2
jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/elixir:1.4.5
        environment:
          MIX_ENV: test
          DATABASE_USERNAME: postgres
      - image: circleci/postgres:9.4-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: dev_bot_test
          POSTGRES_PASSWORD:

    working_directory: ~/app

    steps:
      - checkout

      - run: mix local.hex --force
      - run: mix local.rebar --force

      - restore_cache:
          keys:
            - v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
            - v1-mix-cache-{{ .Branch }}
            - v1-mix-cache

      - restore_cache:
          keys:
            - v1-build-cache-{{ .Branch }}
            - v1-build-cache

      - run: mix do deps.get, compile

      - save_cache:
          key: v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths: "deps"

      - save_cache:
          key: v1-mix-cache-{{ .Branch }}
          paths: "deps"

      - save_cache:
          key: v1-mix-cache
          paths: "deps"

      - save_cache:
          key: v1-build-cache-{{ .Branch }}
          paths: "_build"

      - save_cache:
          key: v1-build-cache
          paths: "_build"

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run: mix test

      - store_test_results:
          path: _build/test/espec

      - add_ssh_keys:
          fingerprints:
            - "2e:f9:ea:5d:80:2e:9c:6d:58:6c:67:02:96:14:c4:8d"

      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              deploy_target=dev-bot-production
            elif [ "${CIRCLE_BRANCH}" == "develop" ]; then
              deploy_target=dev-bot-staging
            fi

            if [ -n "$deploy_target" ]; then
              bash .circleci/setup-heroku.sh

              heroku git:remote -a $deploy_target
              git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/$deploy_target.git HEAD:refs/heads/master
              sleep 5
              heroku run mix ecto.migrate -a $deploy_target
              heroku restart
            fi
